language: python
env:
  - DJANGO_VERSION=1.11.2
python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements/tests.txt
  - pip install Django==$DJANGO_VERSION

script: ./runtest.py
